/home/ubuntu/workWebsite/admin_app/admin_app/urls.py:37: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^', include(xadmin.site.urls)),

System check identified some issues:

WARNINGS:
app.Lesson.ltime: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
Performing system checks...

January 11, 2017 - 04:36:01
Django version 1.9.11, using settings 'admin_app.settings'
Starting development server at http://0.0.0.0:7788/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f56c5111cf8>
Performing system checks...

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workWebsite/admin_app/admin_app/urls.py", line 19, in <module>
    from app import views
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 116
    return response_with_json(data,request.method)
                                                 ^
IndentationError: unindent does not match any outer indentation level
Unhandled exception in thread started by <function wrapper at 0x7f04233b8cf8>
Performing system checks...

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/workWebsite/admin_app/admin_app/urls.py", line 19, in <module>
    from app import views
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 116
    return response_with_json(data,request.method)
                                                 ^
IndentationError: unindent does not match any outer indentation level
/home/ubuntu/workWebsite/admin_app/admin_app/urls.py:38: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^mylogin/',views.userLogin),

System check identified some issues:

WARNINGS:
app.Lesson.ltime: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
Performing system checks...

January 11, 2017 - 07:37:24
Django version 1.9.11, using settings 'admin_app.settings'
Starting development server at http://0.0.0.0:7788/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f9957bb4cf8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/management/commands/runserver.py", line 137, in inner_run
    ipv6=self.use_ipv6, threading=threading)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/servers/basehttp.py", line 198, in run
    httpd.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 235, in serve_forever
    r, w, e = _eintr_retry(select.select, [self], [], [],
AttributeError: 'NoneType' object has no attribute 'select'
/home/ubuntu/workWebsite/admin_app/admin_app/urls.py:38: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^mylogin/',views.userLogin),

System check identified some issues:

WARNINGS:
app.Lesson.ltime: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
[11/Jan/2017 07:37:42] "GET /lesson?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F HTTP/1.1" 301 0
Internal Server Error: /lesson/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 145, in getLesson
    return response_with_json(data,request.method)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 34, in response_with_json
    jsondata  = json.dumps(data,separators = (',',':'))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.db.models.fields.related_descriptors.ManyRelatedManager object at 0x7f9e410b8690> is not JSON serializable
[11/Jan/2017 07:37:43] "GET /lesson/?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F HTTP/1.1" 500 85276
[11/Jan/2017 07:37:46] "GET /mylogin/?username=admin&password=ilove2017 HTTP/1.1" 200 80
[11/Jan/2017 07:37:46] "GET /lesson/?name= HTTP/1.1" 200 2
Internal Server Error: /lesson/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 145, in getLesson
    return response_with_json(data,request.method)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 34, in response_with_json
    jsondata  = json.dumps(data,separators = (',',':'))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.db.models.fields.related_descriptors.ManyRelatedManager object at 0x7f9e41025950> is not JSON serializable
[11/Jan/2017 07:37:56] "GET /lesson/?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F&token= HTTP/1.1" 500 85466
[11/Jan/2017 07:38:05] "GET /lesson?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F&token= HTTP/1.1" 301 0
Internal Server Error: /lesson/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 145, in getLesson
    return response_with_json(data,request.method)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 34, in response_with_json
    jsondata  = json.dumps(data,separators = (',',':'))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.db.models.fields.related_descriptors.ManyRelatedManager object at 0x7f9e410b83d0> is not JSON serializable
[11/Jan/2017 07:38:05] "GET /lesson/?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F&token= HTTP/1.1" 500 85466
Internal Server Error: /lesson/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.11-py2.7.egg/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 145, in getLesson
    return response_with_json(data,request.method)
  File "/home/ubuntu/workWebsite/admin_app/app/views.py", line 34, in response_with_json
    jsondata  = json.dumps(data,separators = (',',':'))
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <django.db.models.fields.related_descriptors.ManyRelatedManager object at 0x7f9e41055a10> is not JSON serializable
[11/Jan/2017 07:38:36] "GET /lesson/?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F&token= HTTP/1.1" 500 85466
/home/ubuntu/workWebsite/admin_app/admin_app/urls.py:38: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^mylogin/',views.userLogin),

System check identified some issues:

WARNINGS:
app.Lesson.ltime: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
[11/Jan/2017 07:44:14] "GET /lesson/?name=%E5%B5%8C%E5%85%A5%E5%BC%8F%E7%B3%BB%E7%BB%9F HTTP/1.1" 200 145
